### ISSUE TITLE
Product Image/shop image and Details

### ISSUE THREAD

**Issue by vivianegwu** [Cornerstock-App/mvp-frontend#7]
It is important that the retailers be able to upload product image alongside the product image. It is also important that retails be able to add their shop image as well as add the details of their shop in the merchant/vendor part of the retailer Dashboard which should be renamed Add Shop.

Extra attention is needed here as we want the retailers to start onboarding their product this weekend. We hope that this deliverable should be meet on or before Friday to speed up the progress.

**Comment by Tumo505** [comment]
im on it
